# Generated by Django 4.2.24 on 2025-10-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('price', models.IntegerField(default=0)),
                ('descrition', models.TextField()),
                ('available', models.IntegerField()),
            ],
        ),
    ]
