# Generated by Django 4.2.24 on 2025-10-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productschema',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AddField(
            model_name='productschema',
            name='remaining',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='productschema',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productschema',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.11, max_digits=15),
        ),
    ]
