# Generated by Django 4.2.24 on 2025-10-03 06:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_descrition_productschema_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productschema',
            name='title',
        ),
        migrations.AddField(
            model_name='productschema',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('GROCERY', 'Grocery'), ('HOME_APPLIANCES', 'Home Appliances'), ('BOOKS', 'Books'), ('TOYS', 'Toys'), ('SPORTS', 'Sports'), ('BEAUTY', 'Beauty'), ('HEALTH', 'Health'), ('AUTOMOTIVE', 'Automotive'), ('MUSIC', 'Music'), ('MOVIES', 'Movies'), ('GAMES', 'Games'), ('FURNITURE', 'Furniture'), ('JEWELRY', 'Jewelry'), ('OTHER', 'Other')], default='Electronics', max_length=100),
        ),
        migrations.AlterField(
            model_name='productschema',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('99.11'), max_digits=15),
        ),
    ]
