# Generated by Django 4.2.24 on 2025-10-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productschema_title_productschema_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productschema',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
