# Generated by Django 5.2.7 on 2025-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productschema_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productschema',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('GROCERY', 'Grocery'), ('HOME_APPLIANCES', 'Home Appliances'), ('BOOKS', 'Books'), ('TOYS', 'Toys'), ('SPORTS', 'Sports'), ('BEAUTY', 'Beauty'), ('HEALTH', 'Health'), ('AUTOMOTIVE', 'Automotive'), ('MUSIC', 'Music'), ('MOVIES', 'Movies'), ('GAMES', 'Games'), ('FURNITURE', 'Furniture'), ('JEWELRY', 'Jewelry'), ('CARS', 'Cars'), ('OTHER', 'Other')], default='Electronics', max_length=100),
        ),
    ]
